server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          predicates:
            - Path=/auth/**
          uri: http://localhost:9090
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/auth-service
        - id: userprofile-service
          predicates:
            - Path=/user-profile/**
          uri: http://localhost:9091
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/user-profile-service
        - id: mail-service
          predicates:
            - Path=/mail/**
          uri: http://localhost:9092
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mail-service
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
