server:
  port: 9092
spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: email-service
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgejava8
    password: bilgeadmin*
  mail:
    username: javaboostbilge@gmail.com
    password: ${EMAIL_PASS}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
