server:
  port: 9091

spring:
  zipkin:
    enable: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: java8SocialMedia
      username: Java8User
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgejava8
    password: bilgeadmin*

openfeign:
  auth-manager-url: http://localhost:9090/api/v1/auth